Mobx 6
electron/fiddle pull request #1061
Opened 2022-04-26 21:19 UTC by erickzhao

2022-04-28 06:44 UTC, BlackHole1 requested changes

2022-04-28 06:44 UTC, BlackHole1 commented on tests/renderer/components/commands-address-bar-spec.tsx
> +    const instance: any = wrapper.instance() as any;
```suggestion
    const instance = wrapper.instance() as any;
```

2022-04-28 06:44 UTC, BlackHole1 commented on tests/renderer/components/commands-address-bar-spec.tsx
> +    const instance: any = wrapper.instance() as any;
Above

2022-04-28 06:48 UTC, BlackHole1 commented
Perhaps it would be better if we used the following?

``` ts
// AddThemeDialog.tsx
export class AddThemeDialogComponent {
  // code
}
export const AddThemeDialog = observer(AddThemeDialogComponent);


// AddThemeDialog-spec.tsx
const wrapper = shallow(<AddThemeDialog appState={store as any} />);
const instance = wrapper.instance() as AddThemeDialogComponent;
```

2022-05-16 16:51 UTC, ckerr reviewed
Even in "hide whitespace" mode, it seems like a lot of this diff is caused by line wrap changes :roll_eyes: This PR isn't as scary as it initially looked

2022-05-16 16:55 UTC, ckerr approved these changes
Looks fine to me. The only thing I don't like abou this PR is the reversion from specific types to `any` but as per the description that seems to be unavoidable for now.

I don't have any extra change requests that weren't already discussed by @BlackHole1

2022-05-16 19:19 UTC, erickzhao commented
FWIW the `:any` changes in our specs will likely be solved with the migration from Enzyme to RTL: https://github.com/electron/fiddle/pull/1064

2022-05-19 03:07 UTC, merged