perf: improve VersionSelect performance
electron/fiddle pull request #1113
Opened 2022-06-22 12:59 UTC by codebytere

Closes https://github.com/electron/fiddle/issues/1112.

Virtualizes list rendering, thereby improving perf ~10x for large lists.

2022-06-22 15:37 UTC, BlackHole1 approved these changes
Wow. So cool!

2022-06-23 02:25 UTC, BlackHole1 commented
Because of the changes to the `yarn.lock` file, it is best not to merge this PR for now. This is because it can lead to conflicts at https://github.com/electron/fiddle/pull/1109 that are difficult to resolve.
So it's best to wait for https://github.com/electron/fiddle/pull/1109 to merge first

2022-06-23 02:26 UTC, BlackHole1 requested changes

2022-06-23 02:26 UTC, BlackHole1 commented on package.json
> +    "@types/react-window": "^1.8.5",
Move to `devDependencies`

2022-06-23 06:34 UTC, codebytere commented
@BlackHole1 that PR is still in a draft state and the lockfile changes in this PR are very minimal - i'm not quite sure i understand why we would pend this smaller change on that much bigger one given it's quite far from being in a mergeable state?

2022-06-23 09:05 UTC, dsanders11 commented
Agreed with @codebytere here. #1109 is still draft and may take a little while to land, and once finalized, due to the large `yarn.lock` changes I plan to do them as a separate commit I'll push to that branch anyway since we're usually weary about large, hard to review `yarn.lock` changes. So I wouldn't worry about merge conflicts on `yarn.lock` with #1109.

2022-06-24 02:18 UTC, BlackHole1 commented
@codebytere @dsanders11 Okey.

2022-06-24 02:18 UTC, BlackHole1 approved these changes

2022-06-24 02:20 UTC, merged