fix: disable right click contextMenu in settings page
electron/fiddle pull request #1115
Opened 2022-06-22 16:05 UTC by aryanshridhar

Minor commit to fix #1070.
Edit: Not sure on how to mock the `contextMenu` behavior.

2022-06-22 22:58 UTC, dsanders11 requested changes
Overall LGTM, couple minor comments. I think there's a lot more issues with the contextmenu throughout Fiddle (it's in a lot of places that probably don't make sense) but this is a step in the right direction.

2022-06-22 22:58 UTC, dsanders11 commented on tests/renderer/components/settings-spec.tsx
>      // check if event listener is removed upon unmount
Let's update this comment to be "// check if event listeners are removed upon unmount" now that there's multiple.

2022-06-22 22:58 UTC, dsanders11 commented on tests/renderer/components/settings-spec.tsx
```suggestion

    // trigger mock 'contextmenu' event
    const preventDefault = jest.fn();
    map.contextmenu({ preventDefault });
    expect(Object.keys(map)).toHaveLength(2); // {'keyup','contextmenu'}
    expect(preventDefault).toHaveBeenCalled();

```

I haven't tested it, but you could try that to get a bit of test coverage. 🙂

2022-09-22 01:36 UTC, BlackHole1 approved these changes
LGTM

2022-10-20 01:38 UTC, dsanders11 approved these changes

2022-10-20 01:43 UTC, merged