feat: Add filter section for "not-downloaded" button #1097
electron/fiddle pull request #1202
Opened 2022-10-30 15:32 UTC by stoichy

![Screenshot from 2022-10-30 17-25-58](https://user-images.githubusercontent.com/40964982/198886990-ca98e3fe-4016-4978-9097-409c6f3f4e25.png)

2022-10-30 20:59 UTC, stoichy commented
Issue #1097

2022-10-31 19:08 UTC, aryanshridhar requested changes
Thanks for working on it 👍 
Left a few minor comments below.

2022-10-31 19:08 UTC, aryanshridhar commented on src/renderer/components/settings-electron.tsx
> +        <FormGroup label="Channels">
Let's add back the `:` to keep it consistent with previous UI.

2022-10-31 19:08 UTC, aryanshridhar commented on src/renderer/components/settings-electron.tsx
> +     * Renders the various options for which versions should be displayedq
Typo?

2022-10-31 19:08 UTC, aryanshridhar commented on src/renderer/components/settings-electron.tsx
> +        <FormGroup inline={true} label="Filters:">
To keep the design similar to `Channels` formgroup, `inline={true}` can be safely removed.

2022-11-06 21:10 UTC, stoichy commented
Fixed, please have another look

2022-11-07 16:17 UTC, codebytere approved these changes

2022-11-07 17:55 UTC, aryanshridhar approved these changes

2022-11-08 01:55 UTC, merged