fix: Replace deprecated Tooltip and Popover components with Tooltip2 …
electron/fiddle pull request #1667
Opened 2024-12-15 03:48 UTC by Santhoshmani1

# Closes #1095 

## fix: Replace deprecated Tooltip and Popover components with Tooltip2

- Replaced the `Popover` component in the `src/renderer/components/commands-action-button.tsx`to `Popover2` and
- `Tooltip` components in the `src/renderer/components/settings-electron.tsx` & `src/renderer/components/version-select.tsx` to `Tooltip2`.

2024-12-16 10:36 UTC, codebytere requested changes
Tests need to be updated; the changes are also not drop-in and likely require other refactoring!

2024-12-17 10:47 UTC, Santhoshmani1 commented
I have updated the snapshots to correctly test for Tooltip2 components. 

I have gone through the Tooltip2 & Poppver2 migration guide https://github.com/palantir/blueprint/wiki/Popover2-migration to see any additional changes required for the project which needs to be done.

2024-12-17 14:18 UTC, codebytere approved these changes

2024-12-17 20:04 UTC, erickzhao approved these changes
LGTM :shipit: 

Thanks for the contribution @Santhoshmani1!

2024-12-17 20:04 UTC, merged