feat: allow setting gist description
electron/fiddle pull request #492
Opened 2020-09-25 02:20 UTC by codebytere

Closes https://github.com/electron/fiddle/issues/477.

This introduces a means to set a custom description for each Gist that's published to GitHub. This is useful when creating many gists since they're hard to differentiate with the same name.

Before adding tests there's a few outstanding question i'd love feedback on:
1) Should we ask for a brief description every time? Right now you can just click 'Ok' without entering anything and it will default to `Electron Fiddle Gist` as the description (as was the case previously)
2) Is this the UI that we think is best?

<img width="1310" alt="Screen Shot 2020-09-24 at 7 16 23 PM" src="https://user-images.githubusercontent.com/2036040/94219138-f3632080-fe9a-11ea-8d68-cc60f0603560.png">

2020-09-29 22:34 UTC, erickzhao reviewed
I feel like this UI is good enough to ship -- I don't have any issues with the way it's handled!

2020-09-30 03:02 UTC, codebytere commented
@erickzhao should be good to go!

2020-10-07 23:54 UTC, erickzhao requested changes

2020-10-07 23:54 UTC, erickzhao commented on src/renderer/components/commands-action-button.tsx
> +    return appState.genericDialogLastInput ?? 'Electron Fiddle Gist';
The Okay button here does the same thing as the Skip one. 

If we want a true skip, this should also short-circuit to `Electron Fiddle Gist` if  `appState.genericDialogLastResult` is false.

However, I'd personally be okay with not having a `Skip` button altogether, and just publishing the placeholder if someone presses "Okay" without entering a string.

2020-10-07 23:54 UTC, erickzhao commented on src/renderer/components/commands-action-button.tsx
> +    appState.setGenericDialogOptions({
Maybe set `ok: 'Publish'` so that the copy is clearer in the dialog.

2020-10-07 23:54 UTC, erickzhao commented on src/renderer/components/dialog-generic.tsx
> +    const shouldShowInput = wantsInput && placeholder;
Would it make sense to make this placeholder optional?

2020-10-08 17:56 UTC, erickzhao approved these changes

2020-10-08 18:20 UTC, merged