Add checkmark to keep track of current open Fiddle
electron/fiddle pull request #507
Opened 2020-10-21 09:40 UTC by JordanTroutman

Addressing Issue #282.  I added functionality to put a checkmark that keeps track of the current open Fiddle in `Show Me > Electron APIs`.  Each item within the `MenuItem` has the `radio` type.

2020-10-23 23:04 UTC, erickzhao requested changes
Hey @JordanTroutman!

So this is a good start, but the `radio` MenuItem type unfortunately doesn't fulfill all of our requirements here. A few acceptance criteria that need to be done:

1) There should be no active checkbox when no Demo is selected.

Unfortunately, this is a limitation in the Chromium model for the `radio` model (see https://github.com/electron/electron/issues/21292#issuecomment-561923188), so this means that the checkboxes need to be managed programatically.

2) When loading another Fiddle, the checkboxes should be reset.

If we load a Fiddle from another source (remote Gist, New Fiddle, or local folder), the ticked MenuItem should be cleared.

3) When loading more than 1 window, the checkboxes should be adjusted accordingly.

Let's say we have two Electron Fiddle windows opened, one of them on the Debugger demo and one on the TouchBar demo, swapping between windows should tick the correct MenuItem for each window.

2020-10-25 23:42 UTC, vhashimotoo reviewed
Since I'm not really known the history of the request so I'm just reporting some additions and bug report:

When you open two windows and choose on the first some another example, and on the second another example that not on window 1, you get that both windows have selected examples from 1 or 2.

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +  active_key: string | null,
Let's use camelCase

```suggestion
  activeKey: string | null,
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +      checked: key == active_key,
Why we can't use `===` here?

```suggestion
      checked: key == activeKey,
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +      return getShowMeMenuItem(subkey, item[subkey], active_key);
```suggestion
      return getShowMeMenuItem(subkey, item[subkey], activeKey);
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +function getShowMeMenu(active_key: string | null): MenuItemConstructorOptions {
```suggestion
function getShowMeMenu(activeKey: string | null): MenuItemConstructorOptions {
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +  ).map((key) => getShowMeMenuItem(key, SHOW_ME_TEMPLATES[key], active_key));
```suggestion
  ).map((key) => getShowMeMenuItem(key, SHOW_ME_TEMPLATES[key], activeKey));
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +export function setupMenu(active_key: string | null = null) {
```suggestion
export function setupMenu(activeKey: string | null = null) {
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +  menu.splice(menu.length - 1, 0, getTasksMenu(), getShowMeMenu(active_key));
```suggestion
  menu.splice(menu.length - 1, 0, getTasksMenu(), getShowMeMenu(activeKey));
```

2020-10-25 23:42 UTC, vhashimotoo commented on src/main/menu.ts
> +export function setupMenu(active_key: string | null = null) {
Also since `activeKey` is unused under `index.ts`, why not use `activeKey?: string | null`

2020-10-26 00:40 UTC, JordanTroutman commented
@vhashimotoo Can you explain a little more of exactly what you tried? I just opened two windows and clicked a different example for each window.  Focusing on a window ticked the appropriate example.

2020-10-26 10:40 UTC, vhashimotoo commented
This seems reproduced very weirdly, you can check the gif below. You need to have two windows and on the first window select example, second shouldn't take the value of the first, but if you select example on the second window the value is changed also in the first window.

![recording](https://user-images.githubusercontent.com/24681191/97162813-c56e4600-1790-11eb-8bcc-ab52f6d6bdae.gif)

2020-10-27 14:35 UTC, JordanTroutman commented
![electron-gif](https://user-images.githubusercontent.com/29002992/97316417-17ba7000-1840-11eb-95af-783aac8ecb20.gif)
This is what it looked like on my Macbook...is there a difference between OS when using menus?

2020-10-27 23:50 UTC, erickzhao commented
@JordanTroutman I can also repro on my Windows VM. I'll try to investigate a bit deeper soon.

2020-10-28 01:20 UTC, erickzhao requested changes
A few general comments, unrelated to the Windows bug pointed above.

2020-10-28 01:20 UTC, erickzhao commented on src/main/windows.ts
> +    browserWindow?.webContents.send(IpcEvents.MENU_IPC_RENDER);
Can we use the `IpcMainManager` and `IpcRendererManager` modules to handle IPC events?

2020-10-28 01:20 UTC, erickzhao commented on src/main/windows.ts
> +  ipcMain.on(IpcEvents.MENU_IPC_MAIN, (_, result) => {
This IPC event will duplicate on each window creation. Should probably go elsewhere.

2021-08-11 16:25 UTC, erickzhao commented
superseded by #705

2021-08-11 16:25 UTC, closed without merging